module.exports = {
	imgPath: {
		path1: "dist/img/i18nImgs/index_en.jpg",
		path2: "dist/img/i18nImgs/baipishuxiazai_en.png",
		path3: "dist/img/i18nImgs/privteOver_en.png",
		path4: "dist/img/i18nImgs/userBanner_en.jpg",
		path5: "dist/img/i18nImgs/plate_en.png",
		path6: "dist/img/i18nImgs/vote_en.png",
		banner1: "dist/img/i18nImgs/banner1.jpg",
		banner2: "dist/img/i18nImgs/vote_en.png",
		banner3: "dist/img/i18nImgs/banner3_en.png",
		banner4: "dist/img/i18nImgs/banner4_en.png",
		ChinaRegion: "dist/img/i18nImgs/ChinaRegion_en.png",
		Entrance: "dist/img/i18nImgs/Entrance_en.png",
		letter: "dist/img/i18nImgs/letter_en.png",
		rw_banner: "dist/img/i18nImgs/rw_banner_en.png",
		sign: "dist/img/i18nImgs/sign_en.png",
	},
	message: {
		quit: "EXIT",
		main: 'Home',
		info: "White Paper",
		team: "Team",
		shop: "PCO",
		apps: "Application",
		news: "News",
		notice: "Announcement",
		knowledge: "Coin Say",
		login: "Log in",
		regist: "Register",
		pubShop: "Public placement",
		priShop: "Private placement",
		news1: "Hot News",
		news2: "Summit",
		news3: "Leaders",
		news4: "Technology ",
		lang1_1: "Vote",
		lang1: "Community",
		lang2: "Constant amount",
		lang3: " taking the astronomical year of the earth as the constant amount",
		lang4: "Only output",
		lang5: "marketing according to global separation and mining",
		lang6: "Real landing",
		lang7: "the global light game platform is landing",
		lang8: "Du Zhanpeng",
		lang9: "Shu Yu ",
		lang10: "Zhang Hongzhong",
		lang11: "Gabriel",
		lang12: "Tang Zhenzhong",
		lang13: "Tian Xiao",
		lang14: "Chinese",
		lang15: "American",
		lang16: "Chinese Taiwanese",
		lang17: "Tsinghua University</br>Master of Computer Applications</br>Education Software Expert</br>Expert in Block Chain Applications</br>Responsible for the overall project",
		lang18: "Brown UniversityMaster of Computer Engineering</br>Technical Expert in Block Chain</br>Responsible for technical framework",
		lang19: "National Tsing Hua University</br>Department of Mathematics, Undergraduate</br>Responsible for numerical values",
		lang20: "Beijing Institute of Technology</br>Computer Application, Undergraduate</br>Responsible for platform development",
		lang21: "Worked for international game companies such as Gameloft and Time Warner Entertainment; responsible for product distribution line; qualified with good international view, insight, high-end decisive ability, data analysis ability, logical thinking, strong market sensibility and professional judging power.",
		lang22: "Worked for public companies such as Forgame and Baidu; responsible for customer services at product operational level; playing a leading role in the research, development and operation of products like Zhetian (《遮天》） and Qingshiqingyuan (《倾世情缘》) with tens of millions of monthly statement; successfully distributed Havoc in Heaven OL (《大闹天宫OL》), a film-animation linkage product, worth of hundreds of millions of monthly statement, by his team; qualified with abundant practical experience and deep understanding on game research and development, platform distribution and the internet industry.",
		lang23: "Operation Team",
		lang24: "Technical Team",
		lang25: "Click to buy",
		lang26: "Public placement link",
		lang27: "●&nbsp;&nbsp; Private Members can only purchase</br>●&nbsp;&nbsp; Greenwich Mean Time</br>●&nbsp;&nbsp; November 8, 2017 from 13:00 to November 9, 2017 at 13:00 for a total of 24 hours.</br>",
		lang28: "●&nbsp;&nbsp;The first public placement is expected to be from 13:00 on February 15, 2018 to 13:00 on February 16, 2018 GMT, totally 24 hours.</br>●&nbsp;&nbsp;The second public placement is expected to be from 13:00 on May 15, 2018 to 13:00 on May 16, 2018 GMT, totally 24 hours.</br>●&nbsp;&nbsp;The third public placement is expected to be from 13:00 on August 15, 2018 to 13:00 on August 16, 2018 GMT, totally 24 hours.</br>●&nbsp;&nbsp;The fourth public placement is expected to be from 13:00 on November 15, 2018 to 13:00 on November 16, 2018 GMT, totally 24 hours.</br>●&nbsp;&nbsp;Public placement stage: 8% will be used for public placement, which will get started a quarter after TTC is listed at the Exchange.</br>●&nbsp;&nbsp;High-price distribution: It will be put on sale on the official website at the highest price at the Exchange of last quarter; there are totally 36,400 time treaty coins and the unsold part are planned to enter into the mining pool.</br>●&nbsp;&nbsp;Each quarter, there will be 1 public placement, with 2% raised capital used for research and development; there will be only 4 placements.",
		lang29: " Application",
		lang30: "Game Industry",
		lang32: "Coin Say",
		lang33: "About to open up..",
		lang34: "Chinese</br>Download",
		lang35: "English</br>Download",
		lang35_JP: "Japanese</br>Download",
		Countdown: "Countdown",
		lang36: "Purchase after login",
		lang37: "Private equity  ended",
		plates1: "game plate",
		plates2: "TT dig",
		plates3: "China",
		plates4: "Japan",
		plates5: "Europe and America",
		plates6: "hong kong macao and taiwan",
		plates7: "Philippines",
		plates8: "Temporarily not opend",
		plates9: "Liyu light game platform",
		lang38: "Real Name",
		lang39_1: "ETHAddress",
		lang39_2: "BTCAddress",
		lang40: "Signature",
		lang41: "Blank",
		lang42: "Save",
		lang43: "Warm Promp",
		lang44: "Digital Assets",
		lang45: "Confirm",
		lang46: "User Center",
		lang47: "TTC Query",
		lang48: "User ID",
		lang49: "Alias",
		lang50: "Invitation",
		lang51: "Extension Link",
		lang52: "Extension code",
		lang53: "Cards",
		lang54: "Game ",
		lang55: "Film-television ",
		lang56: "Finance ",
		lang57: "Global light games platform",
		lang58: "Global broadcasting platform",
		lang59: "Crowd-funding for global dreams",
		lang60: "Sign in",
		lang61: "Invitation",
		lang62: "Coin usage",
		lang63: "Coin advisory",
		lang64: "Coin vote",
		lang65: "Coin forum",
		lang66: "Community report",
		lang67: "TTC global official website",
		lang68: "Popular topic",
		lang69: "End time",
		lang70: "People participation",
		lang71: "To be continued",
		lang72: "Block chain",
		lang73: "Release time",
		lang74: "View more",
		lang75: "Till the end",
		lang76: "Loading",
				lang77: "chat room",
				lang78: "task center",
		lang79: "My attention",
		lang80: "Setting",
			lang81: "Contact Information",
		lang82: "Email:",
	},
	user: {
		"lang1": "account",
		"lang1_phone": "phone number",
		"lang1_email": "email address",
//		"lang1": "phone number",
		"lang2": "Password",
		"lang3": "Reset Passwords",
		"lang4": "Login",
		"lang5": "Register",
		"lang6": "Please enter password",
		"lang7": "verification code",
		"lang7_2": "Invitation Code",
		"lang8": "Confirm password",
		"lang9": "Sent",
		"lang10": "User name must be email address",
		"lang11": "The password must be composed of at least 8 and at most 20 characters",
		"lang12": "Sending",
		"lang13": "Sent",
		"lang14": "Resend",
		"lang15": "Invitation Code can not be empty",
		"lang16": "Reset Passwords",
		"lang17": "attestation",
		"lang18": "authorized",
		"lang19": "Unauthorized",
		"lang20": "copy",
		"lang21": "success",
		"lang22": "invited",
		"lang23": "Promotion course",
		"lang24": "TTC account balance",
	},
	vote: {
		"lang1": "Editior vote",
		"lang2": "Type",
		"lang3": "Vote title(must fill in)",
		"lang4": "Vote introduction(must fill in)",
		"lang5": "Vote options(0-50characters in length ,at least 2 options)",
		"lang6": "Valid time",
		"lang7": "Vote profit",
		"lang8": "Option template",
		"lang9": "Quantity",
		"lang10": "Percentage",
		"lang11": "Multiple choice",
		"lang12": "Release vote",
		"lang13": "Income for each voter involved",
		"lang14": "Number of options up to 9",
		"lang15": "Voting function only fo platform user participation",
		"lang16": "Log in",
		"lang17": "You have no right to vote period,please contact the administrator if you need to obtain jurisdiction",
		"lang18": "Vote",
		"lang19": "Vote result",
		"lang20": "People",
		"lang21": "Voted",
		"lang22": "Please choose voting option",
		"lang23": "Finished",
		"lang24": "Voting has finished",
		"lang25": "Day",
		"lang26": "Hour",
		"lang27": "Minute",
		"lang28": "Second",
		"lang29": "Release",
		"lang30": "People participation",

	},
	payInfo: {
		"lang1": "Transaction information",
		"lang2": "Copy payment address",
		"lang3": "Payment statement",
		"lang4": "1.Who initiates voting(includ system)needs to pay at least 100 TTC reserve fund，10% flowing into monthly lottery pool，10% is as transation fees，80% awards to voting users",
		"lang5": "2.System will transfer the part of reserve fund which doesn't be consumed to the voting user's platform account",
		"lang6": "3.System has already successfully received  the vote initiating apply ,system will have reviwed and launched online in 1 workday after receiving reserve fund ",
		"lang7": "4.Reserve fund has already consumed or reached the setting end time, voting enters the settlement process",
		"lang8": "Copy successfully",

	},
	sign: {
		"lang1": "Bonus",
		"lang2": "Daily bonus",
		"lang3": "Bonus received ",
		"lang4": "Accumulated bonus",
		"lang5": "Day",
		"lang6": "Accumulate bonus",
		"lang7": "Day，bonus",
		"lang8": "Receive",
		"lang9": "Received",
		"lang10": "Coin knowledge community bonus policy",
		"lang11": "1.Time treaty chain official website coin knowledge“Daily bonus”，each menber can only receive 1 time in one day;",
		"lang12": "2.Member's daily bonus is 1 TTC every day，the number of days in accumulating bonus reach the demands will get extra huge rewards，，every month can receive rewards from numbers of days in accumulating bonus, next monthy is invalid;",
		"lang13": "3.Bonus rewards will be sent to personal user center's wallet digital asset;",
		"lang14": "4.The right of coin knowledge community daily bonus final interpretaion is owned by TTC official website;",
		"lang15": "Succeeded",
		"lang16": "The days in bonus is insufficient",
		"lang17": "Bonus",
	},
	
	
	attention:{
		"lang1":"Unfollow",
		"lang2":"Follow",
		"lang3":"post",
		"lang4":"Please follow after login",
		"lang5":"Followed",
		"lang6":"Unfollowed",
	},
	
	bbs:{
		"lang1":"Hot communities",
		"lang2":"The hottest post",
		"lang3":"Follow",
		"lang4":"Post",
		"lang5":"Creation of a community is only developed for private members at present",
		"lang6":"Please operate after login",
		"lang7":"Not logged in",
		"lang8":"Cancel",
		"lang9":"Login",
		"lang10":"Followed",
		"lang11":"Unfollowed",
	},
	bbsDetail:{
		"lang1":"Follow",
		"lang2":"Chat room",
		"lang3":"Post",
		"lang4":"View posts",
		"lang5":"Excellent posts",
		"lang6":"Activities",
		"lang7":"Top",
		"lang8":"Excellent posts",
		"lang9":"Please enter after login",
		"lang10":"Not logged in",
		"lang11":"Cancel",
		"lang12":"Login",
		"lang13":"Coming soon",
		"lang14":"Please follow after login",
		"lang15":"Followed",
		"lang16":"Unfollowed",
		
	},
	bbsSetting:{
		"lang1":"Community management",
		"lang2":"Set sticky post",
		"lang3":"Top",
		"lang4":"Delete",
	},
	chatRoom:{
		"lang1":"TCC official chat-room",
		"lang2":"Cancel",
		"lang3":"Give bonus",
		"lang4":"Total amount",
		"lang5":"Number of bonus",
		"lang6":"TCC bonus received, please click to collect",
		"lang7":"Put into the bonus",
		"lang8":"Minimum amount of bonus shall be 1 TCC",
		"lang9":"Please enter the total amount of bonus",
		"lang10":"Please enter the number of bonus",
		"lang11":"Minimum amount of each bonus shall be 0.01 TCC",
		"lang12":"Amount",
		"lang13":"Confirm payment",
		"lang14":"Cancel",
		"lang15":"Pay",
		"lang16":"Please enter content",
		"lang17":"Failed",
		"lang18":"items",
	},
	comments:{
		"lang1":"Floor",
		"lang2":"View more",
		"lang3":"Write down your comments ",
		"lang4":"Reply",
		"lang5":"Effective point comments with minimum 15 words",
		"lang6":"Add a comment",
		"lang7":"Please operate after login",
		"lang8":"Not logged in",
		"lang9":"Cancel",
		"lang10":"Log in",
		"lang11":"Failed",
		
		//list
		"lang12":"Post",
		"lang13":"No more reply",
		"lang14":"Published successfully",
		"lang15":"Publish failed",
	},
	createBbs:{
		"lang1":"Create a community",
		"lang2":"Community icon",
		"lang3":"Community name ",
		"lang4":"3-6 characters",
		"lang5":"Community introduction",
		"lang6":"Please briefly describe the characteristics of your community",
		"lang7":"Advertising picture of the community",
		"lang8":"Create a community",
		"lang9":"Select an image",
		"lang10":"Upload",
		"lang11":"Cancel",
		"lang12":"Title can not be blank",
		"lang13":"Content can not be blank",
		"lang14":"Community has been created successfully, under review",
	},
	createPost:{
		"lang1":"Create a post",
		"lang2":"Publish",
		"lang3":"Title",
		"lang4":"Create something new",
		"lang5":"Select an image",
		"lang6":"Upload",
		"lang7":"Cancel",
		"lang8":"Title can not be blank",
		"lang9":"Content can not be blank",
	},
	GrabTTC:{
		"lang1":"TTC bonus",
		"lang2":"Remaining Bonus",
		"lang3":"items",
		"lang4":"The best luck",
	},
	lottery:{
		"lang1":"My lottery",
		"lang2":"TTC lottery",
		"lang3":"Losing lottery",
		"lang4":" No lottery",
		"lang5":"Winning lottery",
	},
	lotteryDetail:{
		"lang1":"TTC lottery",
		"lang2":"The lottery time",
		"lang3":"Winning lottery",
		"lang4":"Losing lottery",
		"lang5":"No lottery",
		"lang6":"Please contact official customer service within three business days",
		"lang7":"Current lottery number",
		"lang8":"My lottery",
	},
	post:{
		"lang1":"Post",
		"lang2":"All replies",
		"lang3":"Please follow after login",
		"lang4":"Followed",
		"lang5":"Unfollowed",
	},
	setting:{
		'lang1':"Logout",
		'lang2':"Lottery created successfully",
	},
	tasks:{
		'lang1':"Do tasks, get TTC coins",
		'lang2':"Earn TTC - publish 1 posts",
		'lang3':"Reward 1 TTC coins",
		'lang4':"This weekend",
		'lang5':"Completed",
		'lang6':"Rewarded",
		'lang7':"To complete",
		'lang8':"Earn TTC-Comment、reply 10 posts",
		'lang9':"Reward 10 TTC coins",
		'lang9_1':"Reward 2 TTC coins",
		'lang9_2':"Reward 5 TTC coins",
		'lang10':"Earn TTC-Follow TTC official community",
		'lang11':"One-off",
		'lang12':"Followed",
		'lang13':"Unfollowed",
		'lang14':"To follow",
		'lang15':"Collected",
		'lang16':"TTC coins",
			'lang17':"register",
		'lang18':"Improve personal information",
	},
	userCenter:{
		'lang1':"Login immediately",
		'lang2':"Please operate after login",
		'lang3':"Not logged in",
		'lang4':"Cancel",
		'lang5':"Login",
	},
	userEdit:{
		"lang1":"Personal information",
		"lang2":"Save",
		"lang3":"User account pictures",
		"lang4":"Select an image",
		"lang5":"Upload",
		"lang6":"Cancel",
	},
	manager:{
		"lang1":"Amount of single bonus shall not be less than 0.01 TTC!",
		"lang2":"Number of bonus shall not be less than 1!",
		"lang3":"Minimum amount is RMB 0.01!",
		"lang4":"Your balance is insufficient!",
		"lang5":"Bonus has expired!",
		"lang6":"The community has been created successfully!",
		"lang7":"The amount or number can not be blank!",
		"lang8":"Insufficient days of sign in!",
	}
	
}