module.exports = {
	imgPath: {
		path1: "dist/img/i18nImgs/index_zh.jpg",
		path2: "dist/img/i18nImgs/baipishuxiazai.png",
		path3: "dist/img/i18nImgs/privteOver.png",
		path4: "dist/img/i18nImgs/userBanner.jpg",
		path5: "dist/img/i18nImgs/plate.png",
		path6: "dist/img/i18nImgs/vote_zh.png",
		banner1: "dist/img/i18nImgs/banner1.jpg",
		banner2: "dist/img/i18nImgs/banner2.jpg",
		banner3: "dist/img/i18nImgs/banner3_zh.png",
		banner4: "dist/img/i18nImgs/banner4_zh.png",
		ChinaRegion: "dist/img/i18nImgs/ChinaRegion_zh.png",
		Entrance: "dist/img/i18nImgs/Entrance_zh.png",
		letter: "dist/img/i18nImgs/letter_zh.png",
		rw_banner: "dist/img/i18nImgs/rw_banner_zh.png",
		sign: "dist/img/i18nImgs/sign_zh.png",
	},
	message: {
		quit: "退出",
		main: '首页',
		info: "白皮书",
		team: "团队介绍",
		shop: "公开发行",
		apps: "落地应用",
		news: "新闻资讯",
		notice: "项目公告",
		knowledge: "币知道",
		login: "登录",
		regist: "注册",
		pubShop: "公募",
		priShop: "私募",
		news1: "即时资讯",
		news2: "行业峰会",
		news3: "领军人物",
		news4: "技术前沿",
		lang1_1: "币投票",
		lang1: "社区入口",
		lang2: "数量永恒",
		lang3: "以地球天文年作为永恒数量",
		lang4: "产出唯一",
		lang5: "以全球分矿和挖矿进行推广",
		lang6: "真实落地",
		lang7: "全球轻游戏平台已经开始落地",
		lang8: "杜展鹏",
		lang9: "术羽",
		lang10: "张红中",
		lang11: "Gabriel",
		lang12: "汤镇中",
		lang13: "田潇",
		lang14: "中国人",
		lang15: "美国人",
		lang16: "中国 台湾",
		lang17: "清华大学</br>计算机应用硕士</br>教育软件专家</br>区块链应用专家</br>负责项目整体",
		lang18: "布朗大学</br>计算机工程硕士</br>区块链技术专家</br>负责技术架构",
		lang19: "台湾清大</br>数学系本科</br>负责数值",
		lang20: "北京理工大学</br>计算机应用本科</br>负责平台开发",
		lang21: "曾任职gameloft，华纳娱乐等国际化游戏公司，负责产品发行线，具有良好的国际化视野前瞻性和高端决策能力、数据分析能力和逻辑思维能力，有很强的市场敏锐性和职业判断力。",
		lang22: "曾任职Forgame，百度等上市公司，负责产品运营级客户服务，主导参与了《遮天》、《倾世情缘》等千万级月流水产品的研发运营，带领团队成功发行了月流水过亿的影游联动产品《大闹天宫OL》，对游戏研发，平台发行及互联网行业有着丰富的实战经验和深刻的理解。",
		lang23: "运营团队",
		lang24: "技术团队",
		lang25: "点击购买",
		lang26: "公募链接",
		lang27: "●&nbsp;&nbsp; 私募仅会员可以申购</br>●&nbsp;&nbsp; 格林尼治时间</br>●&nbsp;&nbsp; 2017 年 11月 08日 13:00 至 2017 年 11 月 09日13:00 共24小时</br>",
		lang28: "●&nbsp;&nbsp;第一次公募预计格林尼治时间 2018 年 2月 15 日 13:00 至 2018 年 2 月 16日13:00 共24小时。 </br> </br>●&nbsp;&nbsp;第二次公募预计格林尼治时间 2018 年 5月 15 日 13:00 至 2018 年 5 月 16日 13:00 共24小时。 </br></br>●&nbsp;&nbsp;第三次公募预计格林尼治时间 2018 年 8月 15 日 13:00 至 2018 年 8 月 16日 13:00 共24小时。 </br> </br>●第四次公募预计格林尼治时间 2018 年 11月 15 日 13:00 至 2018 年 11月 16日 13:00 共24小时。</br> </br>●&nbsp;&nbsp;公募阶段：8%用于公开私募，公募将于TTC上市交易所一个季度后开始。</br> </br>●高价发行：实行上季度交易所最高价官网发售，总计36400w时间币，未售出部分进入矿池。 每季度公开私募一次，每次2% 募集资金用于研发，仅发售四次。",
		lang29: "落地应用",
		lang30: "游戏产业",
		lang32: "币知道",
		lang33: "即将开放..",
		lang34: "中文</br>下载",
		lang35: "英文</br>下载",
		lang35_JP: "日文</br>下载",
		Countdown: "倒计时",
		lang36: "登录后购买",
		lang37: "私募已结束",
		plates1: "全球轻游戏平台",
		plates2: "TT挖矿",
		plates3: "中国区",
		plates4: "日本区",
		plates5: "欧美",
		plates6: "港澳台",
		plates7: "菲律宾区",
		plates8: "暂未开放",
		plates9: "鲤鱼轻游戏平台",
		lang38: "真实姓名",
		lang39_1: "ETH地址",
		lang39_2: "BTC地址",
		lang40: "个性签名",
		lang41: "未填写",
		lang42: "保存",
		lang43: "温馨提示",
		lang44: "数字资产",
		lang45: "确认",
		lang46: "用户中心",
		lang47: "时间条约币查询",
		lang48: "用户ID",
		lang49: "昵称",
		lang50: "邀请",
		lang51: "推广链接",
		lang52: "推广码",
		lang53: "卡包",
		lang54: "游戏行业",
		lang55: "影视行业",
		lang56: "金融行业",
		lang57: "全球轻游戏发行运营平台",
		lang58: "全球动漫影视播出平台",
		lang59: "全球梦想众筹平台",
		lang60: "签到",
		lang61: "邀请",
		lang62: "币应用",
		lang63: "币资讯",
		lang64: "币投票",
		lang65: "币论坛",
		lang66: "社区公告",
		lang67: "TTC全球官网",
		lang68: "热门话题",
		lang69: "结束时间",
		lang70: "人参与",
		lang71: "敬请期待",
		lang72: "区块链",
		lang73: "发布时间",
		lang74: "查看更多",
		lang75: "拖到底啦",
		lang76: "加载中",
		lang77: "聊天室",
		lang78: "任务中心",
		lang79: "我的关注",
		lang80: "设置",
				lang81: "联系方式",
		lang82: "电子邮箱:",
	},
	user: {
		
		"lang1": "账号",
		"lang1_phone": "手机号",
		"lang1_email": "邮箱",
		"lang2": "密码",
		"lang3": "忘记密码",
		"lang4": "登录",
		"lang5": "注册",
		"lang6": "请输入密码",
		"lang7": "验证码",
		"lang7_2": "邀请码(选填)",
		"lang8": "确认密码",
		"lang9": "获取验证码",
		"lang10": "用户名必须为手机号",
		"lang11": "密码8-20位",
		"lang12": "发送中",
		"lang13": "发送成功",
		"lang14": "重新发送",
		"lang15": "邀请码不能为空",
		"lang16": "重置密码",
		"lang17": "认证",
		"lang18": "已认证",
		"lang19": "未认证",
		"lang20": "复制",
		"lang21": "复制成功",
		"lang22": "成功邀请",
		"lang23": "推广有奖教程",
		"lang24": "账户TTC余额",

	},
	vote: {
		"lang1": "编辑投票",
		"lang2": "类型",
		"lang3": "投票标题(必填)",
		"lang4": "投票介绍(必填)",
		"lang5": "投票选项(长度0-50个字符 ,选项至少两条)",
		"lang6": "有效时间",
		"lang7": "投票收益",
		"lang8": "选择模板",
		"lang9": "数量",
		"lang10": "比例",
		"lang11": "多选",
		"lang12": "发布投票",
		"lang13": "每位参与投票者可获得的收益",
		"lang14": "选项最多9项",
		"lang15": "投票功能仅限平台用户参与",
		"lang16": "登录",
		"lang17": "您暂没有权限发起投票,如需获取权限请联系管理员",
		"lang18": "投票",
		"lang19": "投票结果",
		"lang20": "人",
		"lang21": "已投票",
		"lang22": "请选择投票项",
		"lang23": "已结束",
		"lang24": "投票已结束",
		"lang25": "天",
		"lang26": "时",
		"lang27": "分",
		"lang28": "秒",
		"lang29": "发布",
		"lang30": "人参与",

	},
	payInfo: {
		"lang1": "转账信息",
		"lang2": "复制付款地址",
		"lang3": "付款说明",
		"lang4": "1.发起投票的人（包括系统）需要支付最低100TTC的准备金，10%进入月度彩票奖池，10%作为转账费用，80%用于奖励投票用户",
		"lang5": "2.准备金未消耗完部分系统将自动打入投票发布者平台账号内",
		"lang6": "3.系统已成功收到发起投票申请,收到准备金后系统将于一个工作日内完成审核并上线",
		"lang7": "4.准备金已消耗完或者到达设定的结束时间, 投票进入结算流程",
		"lang8": "复制成功",

	},
	sign: {
		"lang1": "月签到",
		"lang2": "签到",
		"lang3": "已签到",
		"lang4": "已累计签到",
		"lang5": "天",
		"lang6": "累计签到",
		"lang7": "天，奖励",
		"lang8": "领取",
		"lang9": "已领取",
		"lang10": "币知道社区会员签到规则",
		"lang11": "1.时间条约链官网币知道社区“每日签到”，一个会员每天总计只能参加1次;",
		"lang12": "2.会员累计签到天数达到要求可获得额外丰厚奖励，当月可领取累积签到天数的奖励，次月无效;",
		"lang13": "3.签到奖励会发送到个人用户中心钱包数据资产中;",
		"lang14": "4.币知道社区每日签到的最终解释权归时间条约链官网;",
		"lang15": "签到成功",
		"lang16": "您的签到天数不足",
		"lang17": "签到领奖",
		
	},
	
	attention:{
		"lang1":"取消关注",
		"lang2":"关注",
		"lang3":"帖子",
		"lang4":"请登录后关注",
		"lang5":"关注成功",
		"lang6":"已取消关注",
	},
	
	bbs:{
		"lang1":"热门社群",
		"lang2":"最热帖",
		"lang3":"关注",
		"lang4":"帖子",
		"lang5":"创建社群目前仅对私募会员开发",
		"lang6":"登陆后操作",
		"lang7":"未登录",
		"lang8":"取消",
		"lang9":"登录",
		"lang10":"关注成功",
		"lang11":"已取消关注",
	},
	bbsDetail:{
		"lang1":"关注",
		"lang2":"聊天室",
		"lang3":"贴子",
		"lang4":"看帖",
		"lang5":"精品",
		"lang6":"活动",
		"lang7":"置顶",
		"lang8":"精品",
		"lang9":"请登录后进入",
		"lang10":"未登录",
		"lang11":"取消",
		"lang12":"登录",
		"lang13":"敬请期待",
		"lang14":"请登录后关注",
		"lang15":"关注成功",
		"lang16":"已取消关注",
		
	},
	bbsSetting:{
		"lang1":"社区管理",
		"lang2":"加精",
		"lang3":"置顶",
		"lang4":"删除",
	},
	chatRoom:{
		"lang1":"TTC官方聊天室",
		"lang2":"取消",
		"lang3":"发红包",
		"lang4":"总金额",
		"lang5":"红包个数",
		"lang6":"收到TTC红包,点击领取",
		"lang7":"塞进红包",
		"lang8":"红包金额最少1TTC",
		"lang9":"请输入红包总金额",
		"lang10":"请输入红包个数",
		"lang11":"每个红包最少0.01TTC",
		"lang12":"金额",
		"lang13":"确认支付",
		"lang14":"取消",
		"lang15":"支付",
		"lang16":"请输入内容",
		"lang17":"发送失败",
		"lang18":"个",
	},
	comments:{
		"lang1":"楼",
		"lang2":"查看更多",
		"lang3":"写下你的评论",
		"lang4":"回复",
		"lang5":"15字起为有效积分评论",
		"lang6":"发表评论",
		"lang7":"登陆后操作",
		"lang8":"未登录",
		"lang9":"取消",
		"lang10":"登录",
		"lang11":"发表失败",
		
		//list
		"lang12":"帖子",
		"lang13":"没有更多回复了",
		"lang14":"发表成功",
		"lang15":"发表失败",
	},
	createBbs:{
		"lang1":"创建社区",
		"lang2":"社群图标",
		"lang3":"社群名称",
		"lang4":"3-6个字符",
		"lang5":"社群介绍",
		"lang6":"请简要描述您的社群特色",
		"lang7":"社群宣传图",
		"lang8":"创建社区",
		"lang9":"选择图片",
		"lang10":"上传",
		"lang11":"取消",
		"lang12":"标题不能为空",
		"lang13":"内容不能为空",
		"lang14":"社群创建成功,审核中",
	},
	createPost:{
		"lang1":"创建帖子",
		"lang2":"发布",
		"lang3":"标题",
		"lang4":"尽情发挥吧",
		"lang5":"选择图片",
		"lang6":"上传",
		"lang7":"取消",
		"lang8":"标题不能为空",
		"lang9":"内容不能为空",
	},
	GrabTTC:{
		"lang1":"TTC红包",
		"lang2":"剩余红包",
		"lang3":"个",
		"lang4":"手气最佳",
	},
	lottery:{
		"lang1":"我的彩票",
		"lang2":"TTC彩票",
		"lang3":"未中奖",
		"lang4":"未开奖",
		"lang5":"已中奖",
	},
	lotteryDetail:{
		"lang1":"TTC彩票",
		"lang2":"开奖时间",
		"lang3":"已中奖",
		"lang4":"未中奖",
		"lang5":"未开奖",
		"lang6":"请三个工作日内联系官方客服",
		"lang7":"本期开奖号码",
		"lang8":"我的彩票",
	},
	post:{
		"lang1":"帖子",
		"lang2":"全部回复",
		"lang3":"请登录后关注",
		"lang4":"关注成功",
		"lang5":"已取消关注",
	},
	setting:{
		'lang1':"退出账号",
		'lang2':"彩票生成成功",
	},
	tasks:{
		'lang1':"做任务领TTC币",
		'lang2':"每周成功发布1篇帖子",
		'lang3':"奖励1个TTC币",
		'lang4':"本周",
		'lang5':"已完成",
		'lang6':"已发放",
		'lang7':"去完成",
		'lang8':"点评、回复10篇帖子",
		'lang9_2':"奖励5个TTC币",
		'lang9_1':"奖励2个TTC币",
		'lang9':"奖励10个TTC币",
		'lang10':"关注TTC官方社群",
		'lang11':"一次性",
		'lang12':"已关注",
		'lang13':"未关注",
		'lang14':"去关注",
		'lang15':"已领取",
		'lang16':"个TTC币",
		'lang17':"注册成为会员",
		'lang18':"完善个人信息(绑定钱包地址)",
		'lang19':"领取",
	},
	userCenter:{
		'lang1':"立即登录",
		'lang2':"登陆后操作",
		'lang3':"未登录",
		'lang4':"取消",
		'lang5':"登录",
	},
	userEdit:{
		"lang1":"个人资料",
		"lang2":"保存",
		"lang3":"用户头像",
		"lang4":"选择图片",
		"lang5":"上传",
		"lang6":"取消",
	}
	
	
	
	
	
}